import {Col, Layout as LayoutAnt, Row} from "antd";
import Head from "next/head";
import {Login} from "@/components/Login/Login";
import styles from 'layouts/Layout/Layout.module.scss'

const {Header, Footer, Content} = LayoutAnt;

const Layout = ({children}) => {
    return (
        <LayoutAnt className={styles.Layout}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;600&display=swap"
                      rel="stylesheet"/>
            </Head>
            <Header className={styles.Layout__header}>
                <Row gutter={[16, 16]} wrap={true} justify={'space-between'} align={'middle'} className={styles.Layout__row}>
                    <Col xs={{span: 24}} sm={10}  className={styles.Layout__col}>
                        <h1 className={styles.Layout__h1}>Тестовое задание для Дестры</h1>
                    </Col>
                    <Col xs={{span: 24}} sm={6}  className={styles.Layout__col}>
                        <Login/>
                    </Col>
                </Row>
            </Header>
            <Content className={styles.Layout__content}>
                {children}
            </Content>
            <Footer className={styles.Layout__footer}>
                <Row justify={"end"} align={"middle"}>
                    <Col span={4}><div className={styles.Layout__footerName}>Тыртычный Влад</div></Col>
                    <Col span={3}><a href="https://hh.ru/resume/91e604a5ff0983cd490039ed1f64667a50796a" target={"_blank"} className={styles.Layout__footerName}>Резюме</a></Col>
                </Row>
            </Footer>
        </LayoutAnt>
    )
}

export default Layout